version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_biblioteca
    restart: always
    environment:
      POSTGRES_USER: usr_biblioteca
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biblioteca
      SPRING_DATASOURCE_USERNAME: usr_biblioteca
      SPRING_DATASOURCE_PASSWORD: minha_senha
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  db_data:
