spring.application.name=BibliotecaApplication

# Ativar console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Mostrar detalhes de erros
server.error.include-message=always
server.error.include-stacktrace=always

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=TRACE