spring.application.name=biblioteca

# Ativar banco Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=usr_biblioteca
spring.datasource.password=minha_senha
spring.datasource.driver-class-name=org.postgresql.Driver

#logging.level.org.h2=DEBUG
#logging.level.org.springframework.jdbc=DEBUG
#logging.level.com.bibliotecalivrosemprestimos=DEBUG

# Configurações JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Mostrar detalhes de erros
server.error.include-message=always
server.error.include-stacktrace=always

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=TRACE